### ISSUE TITLE
PR Curve calculation question

### ISSUE THREAD

**Issue by edkazcarlson** [JeffersonQin/yolo-v1-pytorch#1]
Hi, I was looking for a repo for yolo that was set up well for experiments that I want to do and I found yours.
Was looking through the [code for the plot](https://github.com/JeffersonQin/yolo-v1-pytorch/blob/66c9e7bfca785b0a5812a054d050a9aec0503934/yolo/tests.py#L64) and I noticed that you pump the data from calculate_precision_recall right into the plot, but when I check the output of calculate_precision_recall it seems to output the precision and recall for every bounding box of every image. This gives me some odd PR curves if I don't use pretrained data and have low precision/recall
![image](https://user-images.githubusercontent.com/25288961/234177102-3f3cc530-f10e-4c99-a3ea-8faaca97e534.png)
, want to make sure I'm understanding this correctly.

Also a bit curious about how calculate_average_precision is working, as it [iterates backwards over the output of calculate_precision_recall](https://github.com/JeffersonQin/yolo-v1-pytorch/blob/66c9e7bfca785b0a5812a054d050a9aec0503934/utils/metrics.py#L205) but I'm not sure what the purpose of this is since the order seems to be determined by the order it's output from the dataloader.

Was wondering if you would be open to accepting a PR to change how the PR metrics are done.
Thank you for reading, I noticed you have "If you have any problems or questions, feel free to ask and open issues." in the v2 ver of this repo but not this one so no worries if you don't want to spend any time on the v1.

**Comment by JeffersonQin** [comment]
1. `calculate_precision_recall` calculates every coordinates you see in the plot. You first need to understand how PR is calculated. This would need all samples predicted because we will need to use different confidence as threshold to present the graph.
2. Reason why `calculate_average_precision` is iterating backward is that when calculating mAP, the PR graph is essentially interpolated:
![image](https://user-images.githubusercontent.com/30655701/234178336-8ed24646-b418-4e36-87a8-1444d5c4fb3d.png)
It will calculate the area under the green curve.

Also, I believe the algorithm is correct, because the validation mAP I have is close to the official test mAP calculated from my results.

Feel free to ask if you have any questions. But to be honest, there might be a lot of potential bugs in the code and I am almost forgetting everything since it is the work a year ago. Now I would recommend you to take a look at the v2 or v3 repo as in those repos the code are more organized I believe.

**Comment by edkazcarlson** [comment]
Thanks for the quick response, I'll look more into the newer versions.
